### ISSUE TITLE
my_model function isn't called anywhere

### ISSUE THREAD

**Issue by aishitdharwal** [eklavya112/Call-Or-Not-EToE#2]
If not used, remove the function

**Comment by eklavya112** [comment]
my_model is a reference function which was used to train and validate whereas for our model deployment we have given the whole dataset for training. So new fn was created and my_model is left out.

**Comment by aishitdharwal** [comment]
Remove the function now if not needed anymore

**Comment by eklavya112** [comment]
ok done!
